info:
  contact: {}
paths:
  /:
    get:
      description: Root endpoint with ali ali ali
      responses:
        "200":
          description: hello root!
          schema:
            type: string
      summary: Get Root docs
      tags:
      - default
  /value/{value}:
    get:
      description: Get value by parameter
      parameters:
      - description: Value
        in: path
        name: value
        required: true
        type: string
      responses:
        "200":
          description: 'value is: <value>'
          schema:
            type: string
      summary: Get Value
      tags:
      - default
swagger: "2.0"
